/// <reference types="typed-factorio/settings" />
import {
  AreaMaxSideSetting,
  AreasPerTickSetting,
  MaxResultsSetting,
  NegativeOutputSetting,
  OverlayBorderColorSetting,
  OverlayFillColorSetting,
  RoundToStackSetting,
  ScanAreasDelaySetting,
  ShowHiddenSetting,
  UpdateIntervalSetting,
} from "./setting_names.ts";

data.extend([
  {
    type: "int-setting",
    name: AreasPerTickSetting,
    order: "aa",
    setting_type: "runtime-global",
    default_value: 5,
    minimum_value: 1,
    maximum_value: 500,
  },
  {
    type: "int-setting",
    name: UpdateIntervalSetting,
    order: "ab",
    setting_type: "runtime-global",
    default_value: 180,
    minimum_value: 1,
    maximum_value: 216000,
  },
  {
    type: "int-setting",
    name: ScanAreasDelaySetting,
    order: "ac",
    setting_type: "runtime-global",
    default_value: 5,
    minimum_value: 1,
    maximum_value: 216000,
  },
  {
    type: "int-setting",
    name: MaxResultsSetting,
    order: "ad",
    setting_type: "runtime-global",
    default_value: 1000,
    minimum_value: 0,
  },
  {
    type: "int-setting",
    name: AreaMaxSideSetting,
    order: "ae",
    setting_type: "runtime-global",
    default_value: 512,
    minimum_value: 8,
    maximum_value: 4096,
  },
  {
    type: "bool-setting",
    name: ShowHiddenSetting,
    order: "ba",
    setting_type: "runtime-global",
    default_value: false,
  },
  {
    type: "bool-setting",
    name: NegativeOutputSetting,
    order: "bb",
    setting_type: "runtime-global",
    default_value: false,
  },
  {
    type: "bool-setting",
    name: RoundToStackSetting,
    order: "bc",
    setting_type: "runtime-global",
    default_value: false,
  },
  {
    type: "color-setting",
    name: OverlayBorderColorSetting,
    order: "ca",
    setting_type: "runtime-per-user",
    default_value: { r: 1.0, g: 0.85, b: 0.2, a: 1.0 },
  },
  {
    type: "color-setting",
    name: OverlayFillColorSetting,
    order: "cb",
    setting_type: "runtime-per-user",
    default_value: { r: 1.0, g: 0.85, b: 0.2, a: 0.12 },
  },
]);
